#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend alberta-frontend
        bind *:80
        mode http
        default_backend alberta-backend
backend alberta-backend
        balance roundrobin
        server 6230-web-01 54.144.67.160:80 check
        server 6230-web-02 3.80.71.208:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg
